- name: Set up DnsMasq
  become: true
  tags: 
    - iptables
  block:
    - name: Disable Systemctl
      command: systemctl disable systemd-resolved

    - name: Stop System
      command: systemctl stop systemd-resolved

    - name: Remove resolv config
      command: rm /etc/resolv.conf

    - name: add new /etc/resolv.conf 
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 127.0.0.1
          nameserver 8.8.8.8
          nameserver 8.8.4.4

    - name: Create known hosts config
      shell: |
        sed -i "/127.0.0.1/ a 172.17.0.1 my-registry" /etc/hosts

    - name: Ensure etc/iptables folder exists
      file:
        path: /etc/iptables
        state: directory  
    
    - name: Configure IP Tables
      template: src=rules.v4 dest=/etc/iptables/rules.v4

    - name: Restore IpTables
      shell: 
        cmd: iptables-restore < /etc/iptables/rules.v4
