- hosts: localhost
  become: true
  pre_tasks:
  - name: Update Cache
    apt:
      update-cache: true
    tags:
      - core
      - dnsmasq
      - docker
      - git
  tasks:
  - include: tasks/core.yml
  - include: tasks/git.yml 
  - include: tasks/dnsmasq.yml
  - include: tasks/docker.yml
