- hosts: localhost
  become: true
  pre_tasks:
  - name: Update Cache
    apt:
      update-cache: true
    tags:
      - core
      - dnsmasq
      - docker
      - git
  - name: Wait for sudo
    become: yes
    shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
  tasks:
  - import_tasks: tasks/core.yml
  - import_tasks: tasks/git.yml 
  - import_tasks: tasks/dnsmasq.yml
  - import_tasks: tasks/docker.yml
