version: "3.1"
services:
  registry:
    container_name: registry_container
    image: registry:2.6.1
    volumes:
      - registry:/var/lib/registry
    ports:
      - 5000:5000
    restart: unless-stopped

volumes:
  registry:
